### ISSUE TITLE
感谢大佬移植，但编译后安装出错，不知道问这里对不对，还请大佬帮忙看看

### ISSUE THREAD

**Issue by fox85** [w311ang/openwrt-tcp2udp#1]
root@Multi_Services:~# tcp2udp
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.init()
        github.com/q191201771/tcp2udp/main.go:9 +0xc5

还请大佬帮忙看看

**Comment by w311ang** [comment]
带参数运行`tcp2udp TCP_ADDR UDP_ADDR`，像是`tcp2udp :10014 :10014`

**Comment by fox85** [comment]
感谢，我试试
